# Generated by Django 5.1.5 on 2025-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
