# Generated by Django 5.1.5 on 2025-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_datecrea_ownerdata_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
