# Generated by Django 5.1.5 on 2025-01-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_inventoryitem_imi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='cid',
        ),
    ]
