# Generated by Django 5.1.5 on 2025-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_invoicedetail_price_alter_invoicedetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
