# Generated by Django 5.1.5 on 2025-01-27 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_customerdata_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='date_created',
            new_name='datecrea',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='datec',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
