# Generated by Django 5.1.5 on 2025-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='imi',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
