# Generated by Django 5.1.5 on 2025-02-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinvoicedata',
            name='total_after_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='custinvoicedata',
            name='total_before_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
