# Generated by Django 5.1.5 on 2025-02-08 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_imi'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='datecrea',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
