# Generated by Django 5.1.5 on 2025-01-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplierdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplierdata'),
        ),
    ]
