# Generated by Django 5.1.5 on 2025-01-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_ownerdata_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdata',
            name='cif',
        ),
    ]
