# Generated by Django 5.1.5 on 2025-01-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_ownerdata_cif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplierdata'),
        ),
    ]
