# Generated by Django 5.1.5 on 2025-01-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryitem_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdata',
            name='cif',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplierdata'),
        ),
    ]
