# Generated by Django 5.1.5 on 2025-01-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_ownerdata_cif_alter_inventoryitem_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='imi',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
