# Generated by Django 5.1.5 on 2025-01-31 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_category_name_alter_inventoryitem_imi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='cname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supply',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplierdata'),
        ),
        migrations.AlterField(
            model_name='ownerdata',
            name='cif',
            field=models.CharField(default=0, max_length=35),
        ),
        migrations.AlterField(
            model_name='ownerdata',
            name='firma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierdata',
            name='sname',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateof', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customerdata')),
            ],
        ),
    ]
