# Generated by Django 5.1.5 on 2025-01-31 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_customerdata_cname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='imi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='name',
            field=models.CharField(default=0, max_length=35),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='nie',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customerdata'),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
