# Generated by Django 5.1.5 on 2025-01-31 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_invoicedata_customer_invoicedata_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceData',
            new_name='InvoiceinData',
        ),
    ]
