# Generated by Django 5.1.5 on 2025-01-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_custinvoicedata_datein_custinvoicedata_imi'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinvoicedata',
            name='desc',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='custinvoicedata',
            name='imi',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
