# Generated by Django 5.1.5 on 2025-01-31 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_custinvoicedata_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinvoicedata',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
            preserve_default=False,
        ),
    ]
