# Generated by Django 5.1.5 on 2025-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_custinvoicedata_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='custinvoicedata',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custinvoicedata',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
