# Generated by Django 5.1.5 on 2025-02-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_custinvoicedata_quantity_custinvoicedata_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='datecrea',
        ),
        migrations.AlterField(
            model_name='custinvoicedata',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customerdata'),
        ),
        migrations.AlterField(
            model_name='custinvoicedata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='cname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='cphone',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='imi',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
