# Generated by Django 5.1.5 on 2025-02-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_inventoryitem_datecrea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='cnie',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='cphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='imi',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imi', models.CharField(max_length=20)),
                ('prodname', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customerdata')),
            ],
        ),
    ]
