# Generated by Django 5.1.5 on 2025-02-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_customerdata_cnie_alter_customerdata_cphone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custinvoicedata',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='custinvoicedata',
            name='imi',
        ),
        migrations.RemoveField(
            model_name='custinvoicedata',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='custinvoicedata',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='cust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.custinvoicedata'),
            preserve_default=False,
        ),
    ]
