# Generated by Django 5.1.5 on 2025-02-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_custinvoicedata_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.custinvoicedata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='cust',
            field=models.CharField(max_length=25),
        ),
    ]
