# Generated by Django 5.1.5 on 2025-02-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_invoicedetail_invoice_alter_invoicedetail_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custinvoicedata',
            name='phone',
        ),
    ]
