# Generated by Django 5.1.5 on 2025-02-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_rename_cust_invoicedetail_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='prodname',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='custid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
