# Generated by Django 5.1.5 on 2025-02-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_custinvoicedata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='custid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
