# Generated by Django 5.1.5 on 2025-02-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_invoicedetail_custid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='custid',
            new_name='cusid',
        ),
    ]
