# Generated by Django 5.1.5 on 2025-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_rename_custid_invoicedetail_cusid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='cusid',
            field=models.PositiveIntegerField(),
        ),
    ]
