# Generated by Django 5.1.5 on 2025-02-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_invoicedetail_cusid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='cusid',
            new_name='customer_id',
        ),
    ]
