# Generated by Django 5.1.5 on 2025-02-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_rename_cusid_invoicedetail_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinvoicedata',
            name='customer',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='custinvoicedata',
            name='product',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
