# Generated by Django 5.1.5 on 2025-02-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_custinvoicedata_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='customer_id',
        ),
    ]
