# Generated by Django 5.1.5 on 2025-02-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_remove_custinvoicedata_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinvoicedata',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customerdata'),
        ),
    ]
